# Generated by Django 5.1.8 on 2025-08-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("email_logger", "0003_auto_20200312_1746"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillog",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
